apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctf-frontend-mobile
  labels:
    app: ctf-frontend-mobile
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ctf-frontend-mobile
  template:
    metadata:
      labels:
        app: ctf-frontend-mobile
    spec:
      containers:
      - name: ctf-frontend-mobile
        image: jonhyble/tolerante_esteganografia_mobile:1.0
        ports:
        - containerPort: 5173

---

apiVersion: v1
kind: Service
metadata:
  name: ctf-frontend-mobile-service
  labels:
    app: ctf-frontend-mobile-service
spec:
  selector:
    app: ctf-frontend-mobile
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  sessionAffinity: None