apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tolerante-esteganografia-service-ingress
spec:
  hosts: 
  - '*'
  gateways:
  - ctf-esteganografia-gateway
  http:
  - match:
    - uri:
        prefix: /v1/
    rewrite:
        uri: /
    route:
    - destination:
        host: ctf-frontend-desktop-service
        port:
          number: 5173
  - match:
    - uri:
        prefix: /v2/
    rewrite:
        uri: /
    route:
    - destination:
        host: ctf-frontend-mobile-service
        port: 
          number: 5173